In [5]:
import pandas as pd

df_live = pd.read_csv("D:\\prdp\\Data Analytics\\Live-Market\\Live-Market - Copy.csv")
df_live.sample(5)

,DMD-DateTime,DMD-Date,DMD-Day,DMD-Month,DMD-Year,DMH-Time,DMH-Hours-24,DMH-Minutes,DMT-Month_Name,DMT-Day_Name,...,DMT-FY,Silver_USD_t.oz,Gold_USD_t.oz,USD_INR,Silver_INR_g,Silver_INR_kg,Gold_INR_g,Gold_INR_kg,Eq-NSE,Eq-BSE
7408,05-01-2012 00:00:00,2012-01-05,5,1,2012,00:00:00,0,0,Jan,Thu,...,FY 2011-12,29.063000,1611.900024,52.849998,53.039612,53039.611657,3024.174918,3.024175e+06,4749.950195,15857.08
9920,23-02-2022 00:00:00,2022-02-23,23,2,2022,00:00:00,0,0,Feb,Wed,...,FY 2021-22,24.311001,1906.099976,74.623001,64.504894,64504.893616,5137.410732,5.137411e+06,17063.250000,57232.06
6252,09-05-2007 00:00:00,2007-05-09,9,5,2007,00:00:00,0,0,May,Wed,...,FY 2007-08,13.489000,685.099976,40.613998,8.823459,8823.459378,914.204269,9.142043e+05,NaN,13781.51
8748,02-06-2017 00:00:00,2017-06-02,2,6,2017,00:00:00,0,0,Jun,Fri,...,FY 2017-18,17.243000,1267.000000,64.372299,39.332960,39332.960386,2890.150248,2.890150e+06,9653.500000,31273.29
7275,22-06-2011 00:00:00,2011-06-22,22,6,2011,00:00:00,0,0,Jun,Wed,...,FY 2011-12,36.373001,1546.000000,44.759998,55.620104,55620.104222,2274.869346,2.274869e+06,5278.299805,17550.63

In [13]:
df_silv = pd.read_csv("D:\\prdp\\Data Analytics\\Live-Market\\Silver EFT Historical Data.csv")
df_silv = df_silv[["Date", "SilverETF"]]
df_silv.sample(5)

            Date  SilverETF
1070  11-02-2022      62.36
478   05-07-2024      88.68
16    19-05-2026     253.25
79    11-02-2026     247.37
43    08-04-2026     230.58

In [14]:
df = df_live.join(df_silv, how="left")
df

,DMD-DateTime,DMD-Date,DMD-Day,DMD-Month,DMD-Year,DMH-Time,DMH-Hours-24,DMH-Minutes,DMT-Month_Name,DMT-Day_Name,...,Gold_USD_t.oz,USD_INR,Silver_INR_g,Silver_INR_kg,Gold_INR_g,Gold_INR_kg,Eq-NSE,Eq-BSE,Date,SilverETF
0,03-04-1979 00:00:00,1979-04-03,3,4,1979,00:00:00,0,0,Apr,Tue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.150000,11-06-2026,222.28
1,04-04-1979 00:00:00,1979-04-04,4,4,1979,00:00:00,0,0,Apr,Wed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122.850000,10-06-2026,220.59
2,06-04-1979 00:00:00,1979-04-06,6,4,1979,00:00:00,0,0,Apr,Fri,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123.520000,09-06-2026,231.90
3,07-04-1979 00:00:00,1979-04-07,7,4,1979,00:00:00,0,0,Apr,Sat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.180000,08-06-2026,227.93
4,09-04-1979 00:00:00,1979-04-09,9,4,1979,00:00:00,0,0,Apr,Mon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.300000,05-06-2026,243.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14663,11-06-2026 13:42:48,11-06-2026,11,6,2026,13:42:48,13,42,Jun,Thu,...,4132.000000,95.702499,228.724771,228724.771407,14620.834845,1.462083e+07,23231.050781,74073.593750,NaN,NaN
14664,11-06-2026 13:47:49,11-06-2026,11,6,2026,13:47:49,13,47,Jun,Thu,...,4129.000000,95.702499,229.025536,229025.535583,14610.219524,1.461022e+07,23233.500000,74186.460938,NaN,NaN
14665,11-06-2026 13:52:50,11-06-2026,11,6,2026,13:52:50,13,52,Jun,Thu,...,4127.500000,95.709999,228.778090,228778.090082,14606.056373,1.460606e+07,23224.500000,74153.929688,NaN,NaN
14666,11-06-2026 13:57:52,11-06-2026,11,6,2026,13:57:52,13,57,Jun,Thu,...,4124.799805,95.717499,228.530576,228530.575990,14597.644905,1.459764e+07,23234.849609,74094.328125,NaN,NaN
14667,11-06-2026 14:02:53,11-06-2026,11,6,2026,14:02:53,14,2,Jun,Thu,...,4122.200195,95.709999,228.264961,228264.960930,14587.301862,1.458730e+07,23230.849609,74107.929688,NaN,NaN